### ISSUE TITLE
time estimation rule on issue with priority-1 + bug labels?

### ISSUE THREAD

**Issue by SimonLab** [dwyl/dwylbot#135]
Do we want dwylbot to remind the user to add a time estimation on an issue with a ```priority-1``` and ```bug``` labels? These kind of issues might be difficult to estimate if the bugs are still investigated.

**Comment by samhstn** [comment]
My preference would be that in this scenario, dwylbot shouldn't comment

**Comment by SimonLab** [comment]
I would still add an estimation to the issue. I think this can give a first idea how long the task might take and  the estimation can still be updated later on. But I also understand that dwylbot can be a bit annoying on this kind of issue. Maybe another type of message in this situation? 
"Keep calm and debug. Everything will be fine :+1: (any time estimation for this issue?)"

**Comment by nelsonic** [comment]
@SimonLab _great_ question!
IMO even if there are _many_ unknowns/uncertainties that require investigation, we should _still_ `try` to estimate the time required to solve the issue, even if we end up being _wildly_ incorrect.
What we _need_ is to:
+ [ ] collect as much information as possible about the issue/bug `before` estimating to _maximise_ our understanding prior to estimation. 
+ [ ] make it _clear_ to both the client and team that there are _still_ unknowns and _communicate_ what we are attempting to do to resolve the issue. 
+ [ ] ask for help when the "clock" on your original time estimate runs out! (_@dwylbot could even apply the `help-wanted` on a `P1` after the time estimate label (_time allocation_) expires. 😮  💡 

For example: I _estimated_ that `this` (`P1`) issue/task would take me `T1d` to complete: https://github.com/healthlocker/healthlocker/issues/879 but it has taken me Two Days and I'm _still_ not finished resolving it!

I have been writing comments as I go to keep the team informed of what I'm trying.
I think time _estimation_ is a _fundamental_ communication tool we have when working in teams.
(_even if the "project manager" then keeps asking "**is it done yet**" ... "**will it be done today**" ... "**what's the status of X**" ... because they don't understand how debugging works!!_) 

If we _estimate_ that something will take `T1h` and it ends up taking `T4h`, we should leave a _comment_ explaining why it took longer so everyone is aware of what the complexities are/were.

One of the _biggest_ benefits is that we have a "Scrum Master" who writes code 
and _understands_ that debugging is not "_easy to estimate_". 

So: @dwylbot should  `should` still comment on `P1` if no estimate is given, but should _delay_ commenting for 30mins to avoid "fanning the flames" of the "Production Bug".

**Comment by iteles** [comment]
:arrow_up: @nelsonic I like that, best of both worlds, a good starting point to test.

**Comment by ghost** [comment]
Closing as this question was suitably answered
