### ISSUE TITLE
Unassigned with in-progress label

### ISSUE THREAD

**Issue by SimonLab** [dwyl/dwylbot#71]
If someone is unassigned from an issue and the label "in-progress" is still on the issue, dwylbot should add a comment on the issue

**Comment by ghost** [comment]
@SimonLab this doesn't appear to work

**Comment by SimonLab** [comment]
It's working on my repo:
![image](https://user-images.githubusercontent.com/6057298/27178145-0245cbd2-51c1-11e7-8ce5-410fd6767b07.png)

I've just remove the assignee of the issue (the assignee list is empty) bu left the ``in-progress`` label. Could you try again maybe the deployment of the new version took a bit of time. It takes also around 30s after the event for dwylbot to comment.

**Comment by SimonLab** [comment]
seems to work :arrow_up:

**Comment by ghost** [comment]
Seems to work now - @SimonLab please can we update the text to this:

⚠️ @username the assignee for this issue has been removed with the `in-progress` label still attached. Please remove the `in-progress` label if this issue is no longer being worked on or assign a user to this issue if it is still in progress.

**Comment by ghost** [comment]
This works 👍
